In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
df = pd.read_csv('online_shoppers_intention.csv')

In [3]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [5]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [6]:
for i in df.columns:
    if df[i].dtype == 'object':
        print(df[i].value_counts())

Month
May     3364
Nov     2998
Mar     1907
Dec     1727
Oct      549
Sep      448
Aug      433
Jul      432
June     288
Feb      184
Name: count, dtype: int64
VisitorType
Returning_Visitor    10551
New_Visitor           1694
Other                   85
Name: count, dtype: int64

In [7]:
visitors = pd.get_dummies(df['VisitorType'])
x = pd.concat([df,visitors],axis=1)
x.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue,New_Visitor,Other,Returning_Visitor
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,1,1,1,1,Returning_Visitor,False,False,False,False,True
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,2,2,1,2,Returning_Visitor,False,False,False,False,True
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,4,1,9,3,Returning_Visitor,False,False,False,False,True
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,3,2,2,4,Returning_Visitor,False,False,False,False,True
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,3,3,1,4,Returning_Visitor,True,False,False,False,True

In [8]:
visitors

       New_Visitor  Other  Returning_Visitor
0            False  False               True
1            False  False               True
2            False  False               True
3            False  False               True
4            False  False               True
...            ...    ...                ...
12325        False  False               True
12326        False  False               True
12327        False  False               True
12328        False  False               True
12329         True  False              False

[12330 rows x 3 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [10]:
y = x['Revenue']
y

0        False
1        False
2        False
3        False
4        False
         ...
12325    False
12326    False
12327    False
12328    False
12329    False
Name: Revenue, Length: 12330, dtype: bool

In [11]:
x_new = x.drop(['Revenue','Month','VisitorType'],axis=1)

In [12]:
x_new['Weekend'] = np.asarray(x_new['Weekend'].astype(np.float32))
y = np.asarray(y).astype(np.float32)

In [26]:
x_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  OperatingSystems         12330 non-null  int64
 11  Browser                  12330 non-null  int64
 12  Region                   12330 non-null  int64
 13  TrafficType              12330 non-null  int64
 14  Weekend                  12330 non-null  float32
 15  New_Visitor              12330 non-null  bool
 16  Other                    12330 non-null  bool
 17  Returning_Visitor        12330 non-null  bool
dtypes: bool(3), float32(1), float64(7), int64(7)
memory usage: 1.4 MB

In [14]:
y.shape

(12330,)

In [15]:
x_new.shape

(12330, 18)

In [18]:
model = Sequential()
model.add(Dense(18,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))

model.add(Dense(units=2,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [20]:
model.fit(x_new,y,epochs=100,validation_split=0.1)

Epoch 1/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7200 - loss: 4.1317 - val_accuracy: 0.8070 - val_loss: 6.2800
Epoch 2/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8434 - loss: 1.2454 - val_accuracy: 0.8313 - val_loss: 0.5970
Epoch 3/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8618 - loss: 0.7099 - val_accuracy: 0.8256 - val_loss: 1.0119
Epoch 4/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8530 - loss: 0.9199 - val_accuracy: 0.8273 - val_loss: 1.0579
Epoch 5/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8674 - loss: 0.7430 - val_accuracy: 0.8305 - val_loss: 0.7983
Epoch 6/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8628 - loss: 0.6978 - val_accuracy: 0.6821 - val_loss: 1.9870
Epoch 7/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8685 - loss: 0.6917 - val_accuracy: 0.6302 - val_loss: 2.6519
Epoch 8/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8588 - loss: 0.8096 - val_accuracy: 0.8094 - val_loss: 0.6614
Epoch 9/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8799 - loss: 0.5314 - val_accuracy: 0.8297 - val_loss: 0.7309
Epoch 10/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8714 - loss: 0.5066 - val_accuracy: 0.8183 - val_loss: 0.5215
Epoch 11/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8704 - loss: 0.8772 - val_accuracy: 0.8273 - val_loss: 1.5736
Epoch 12/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8725 - loss: 0.5892 - val_accuracy: 0.8264 - val_loss: 1.2518
Epoch 13/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8707 - loss: 0.5347 - val_accuracy: 0.8256 - val_loss: 0.4712
Epoch 14/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8705 - loss: 0.5144 - val_accuracy: 0.8273 - val_loss: 1.2724
Epoch 15/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8838 - loss: 0.4489 - val_accuracy: 0.7737 - val_loss: 0.7622
Epoch 16/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8692 - loss: 0.8574 - val_accuracy: 0.8321 - val_loss: 0.4805
Epoch 17/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8823 - loss: 0.4272 - val_accuracy: 0.8297 - val_loss: 0.7224
Epoch 18/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8710 - loss: 0.6391 - val_accuracy: 0.8248 - val_loss: 1.6569
Epoch 19/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8703 - loss: 0.5246 - val_accuracy: 0.8321 - val_loss: 0.5297
Epoch 20/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8811 - loss: 0.3925 - val_accuracy: 0.7826 - val_loss: 0.6621
Epoch 21/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8862 - loss: 0.3728 - val_accuracy: 0.8297 - val_loss: 0.5410
Epoch 22/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8760 - loss: 0.4638 - val_accuracy: 0.7948 - val_loss: 0.6076
Epoch 23/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8866 - loss: 0.3445 - val_accuracy: 0.8305 - val_loss: 0.6012
Epoch 24/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8831 - loss: 0.4684 - val_accuracy: 0.8321 - val_loss: 0.6282
Epoch 25/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8804 - loss: 0.3931 - val_accuracy: 0.8337 - val_loss: 0.4511
Epoch 26/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8844 - loss: 0.3579 - val_accuracy: 0.8297 - val_loss: 0.4902
Epoch 27/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8795 - loss: 0.3891 - val_accuracy: 0.8313 - val_loss: 0.8305
Epoch 28/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8838 - loss: 0.3448 - val_accuracy: 0.8264 - val_loss: 0.9568
Epoch 29/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8816 - loss: 0.3475 - val_accuracy: 0.8159 - val_loss: 1.9539
Epoch 30/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8881 - loss: 0.3664 - val_accuracy: 0.8427 - val_loss: 0.4096
Epoch 31/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8865 - loss: 0.3440 - val_accuracy: 0.7916 - val_loss: 0.5851
Epoch 32/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8804 - loss: 0.3389 - val_accuracy: 0.8191 - val_loss: 1.2899
Epoch 33/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8817 - loss: 0.3489 - val_accuracy: 0.8354 - val_loss: 0.4322
Epoch 34/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8892 - loss: 0.3149 - val_accuracy: 0.8240 - val_loss: 0.4169
Epoch 35/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8962 - loss: 0.2883 - val_accuracy: 0.8305 - val_loss: 0.5515
Epoch 36/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8886 - loss: 0.3228 - val_accuracy: 0.8313 - val_loss: 0.4298
Epoch 37/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8902 - loss: 0.3102 - val_accuracy: 0.8354 - val_loss: 0.4432
Epoch 38/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8923 - loss: 0.2929 - val_accuracy: 0.8394 - val_loss: 0.4193
Epoch 39/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8897 - loss: 0.3020 - val_accuracy: 0.8386 - val_loss: 0.4324
Epoch 40/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8944 - loss: 0.2715 - val_accuracy: 0.8345 - val_loss: 0.5133
Epoch 41/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8939 - loss: 0.2726 - val_accuracy: 0.8394 - val_loss: 0.6088
Epoch 42/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8947 - loss: 0.3016 - val_accuracy: 0.8451 - val_loss: 0.3889
Epoch 43/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8968 - loss: 0.2669 - val_accuracy: 0.8362 - val_loss: 0.5334
Epoch 44/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8953 - loss: 0.2669 - val_accuracy: 0.8394 - val_loss: 0.4051
Epoch 45/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9002 - loss: 0.2665 - val_accuracy: 0.8394 - val_loss: 0.4131
Epoch 46/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8995 - loss: 0.2488 - val_accuracy: 0.8386 - val_loss: 0.4111
Epoch 47/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8941 - loss: 0.2657 - val_accuracy: 0.8451 - val_loss: 0.4122
Epoch 48/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8999 - loss: 0.2505 - val_accuracy: 0.7875 - val_loss: 0.4850
Epoch 49/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8945 - loss: 0.2721 - val_accuracy: 0.8378 - val_loss: 0.4080
Epoch 50/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8972 - loss: 0.2551 - val_accuracy: 0.8337 - val_loss: 0.4043
Epoch 51/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9021 - loss: 0.2414 - val_accuracy: 0.8354 - val_loss: 0.3774
Epoch 52/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9009 - loss: 0.2422 - val_accuracy: 0.8337 - val_loss: 0.3830
Epoch 53/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8911 - loss: 0.2549 - val_accuracy: 0.8337 - val_loss: 0.5079
Epoch 54/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9021 - loss: 0.2434 - val_accuracy: 0.8354 - val_loss: 0.4019
Epoch 55/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8998 - loss: 0.2529 - val_accuracy: 0.8329 - val_loss: 0.4147
Epoch 56/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8999 - loss: 0.2399 - val_accuracy: 0.8410 - val_loss: 0.3776
Epoch 57/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8952 - loss: 0.2443 - val_accuracy: 0.8337 - val_loss: 0.3793
Epoch 58/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8965 - loss: 0.2509 - val_accuracy: 0.8435 - val_loss: 0.4011
Epoch 59/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9017 - loss: 0.2445 - val_accuracy: 0.8418 - val_loss: 0.3820
Epoch 60/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9013 - loss: 0.2442 - val_accuracy: 0.8394 - val_loss: 0.4339
Epoch 61/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8975 - loss: 0.2530 - val_accuracy: 0.8508 - val_loss: 0.4133
Epoch 62/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9023 - loss: 0.2420 - val_accuracy: 0.8459 - val_loss: 0.4067
Epoch 63/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9037 - loss: 0.2365 - val_accuracy: 0.8410 - val_loss: 0.3894
Epoch 64/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9060 - loss: 0.2372 - val_accuracy: 0.8402 - val_loss: 0.3782
Epoch 65/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9005 - loss: 0.2393 - val_accuracy: 0.8370 - val_loss: 0.3893
Epoch 66/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8957 - loss: 0.2423 - val_accuracy: 0.8402 - val_loss: 0.4300
Epoch 67/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8984 - loss: 0.2473 - val_accuracy: 0.8467 - val_loss: 0.4073
Epoch 68/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8990 - loss: 0.2404 - val_accuracy: 0.8451 - val_loss: 0.3933
Epoch 69/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9016 - loss: 0.2416 - val_accuracy: 0.8386 - val_loss: 0.3922
Epoch 70/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9010 - loss: 0.2389 - val_accuracy: 0.8451 - val_loss: 0.5082
Epoch 71/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9000 - loss: 0.2453 - val_accuracy: 0.8459 - val_loss: 0.3822
Epoch 72/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9003 - loss: 0.2460 - val_accuracy: 0.8418 - val_loss: 0.3978
Epoch 73/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9082 - loss: 0.2309 - val_accuracy: 0.8459 - val_loss: 0.3817
Epoch 74/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9009 - loss: 0.2330 - val_accuracy: 0.8410 - val_loss: 0.3776
Epoch 75/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9045 - loss: 0.2309 - val_accuracy: 0.8402 - val_loss: 0.3823
Epoch 76/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8999 - loss: 0.2351 - val_accuracy: 0.8467 - val_loss: 0.4003
Epoch 77/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9031 - loss: 0.2324 - val_accuracy: 0.8451 - val_loss: 0.3894
Epoch 78/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9018 - loss: 0.2318 - val_accuracy: 0.8435 - val_loss: 0.3820
Epoch 79/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9034 - loss: 0.2347 - val_accuracy: 0.8386 - val_loss: 0.3880
Epoch 80/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9004 - loss: 0.2383 - val_accuracy: 0.8475 - val_loss: 0.4396
Epoch 81/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9008 - loss: 0.2397 - val_accuracy: 0.8435 - val_loss: 0.3901
Epoch 82/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8980 - loss: 0.2405 - val_accuracy: 0.8402 - val_loss: 0.3804
Epoch 83/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9052 - loss: 0.2290 - val_accuracy: 0.8418 - val_loss: 0.3675
Epoch 84/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8950 - loss: 0.2509 - val_accuracy: 0.8345 - val_loss: 0.3902
Epoch 85/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9014 - loss: 0.2440 - val_accuracy: 0.8402 - val_loss: 0.3900
Epoch 86/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9058 - loss: 0.2286 - val_accuracy: 0.8418 - val_loss: 0.3753
Epoch 87/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9024 - loss: 0.2352 - val_accuracy: 0.8410 - val_loss: 0.3799
Epoch 88/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9008 - loss: 0.2337 - val_accuracy: 0.8427 - val_loss: 0.3830
Epoch 89/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9091 - loss: 0.2272 - val_accuracy: 0.8508 - val_loss: 0.4066
Epoch 90/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9013 - loss: 0.2305 - val_accuracy: 0.8500 - val_loss: 0.4043
Epoch 91/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9063 - loss: 0.2310 - val_accuracy: 0.8410 - val_loss: 0.3770
Epoch 92/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8969 - loss: 0.2416 - val_accuracy: 0.8362 - val_loss: 0.3706
Epoch 93/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9012 - loss: 0.2393 - val_accuracy: 0.8402 - val_loss: 0.3949
Epoch 94/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9011 - loss: 0.2384 - val_accuracy: 0.8410 - val_loss: 0.3943
Epoch 95/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9043 - loss: 0.2281 - val_accuracy: 0.8435 - val_loss: 0.4216
Epoch 96/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8992 - loss: 0.2360 - val_accuracy: 0.8386 - val_loss: 0.4006
Epoch 97/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9037 - loss: 0.2293 - val_accuracy: 0.8248 - val_loss: 0.3898
Epoch 98/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9019 - loss: 0.2342 - val_accuracy: 0.8418 - val_loss: 0.5363
Epoch 99/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9049 - loss: 0.2331 - val_accuracy: 0.8459 - val_loss: 0.3720
Epoch 100/100
347/347 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9003 - loss: 0.2364 - val_accuracy: 0.8459 - val_loss: 0.3802

In [21]:
import os
os.getcwd()

'C:\\Users\\bharg\\my_projects'

In [22]:
model.save('final_shopper_model.keras')

In [42]:
A = [1,2,3,4,5]
arr = np.array(A)

In [44]:
arr

array([1, 2, 3, 4, 5])

In [46]:
A = [1,2,3,4,5,'ind']
arr = np.array(A)

In [48]:
arr

array(['1', '2', '3', '4', '5', 'ind'], dtype='<U11')

In [52]:
for i in arr:
    print(i)

1
2
3
4
5
ind

In [66]:
Input= "This is a test. This test is easy."
frequency={}

In [68]:
for i in Input.split():
    if i in frequency:
        frequency[i] += 1
    else:
        frequency[i] = 1
print(frequency)

{'This': 2, 'is': 2, 'a': 1, 'test.': 1, 'test': 1, 'easy.': 1}

In [76]:
Input2= [[1, 2], [3, 4], [5]]
flattend = [ele for x in Input2 for ele in x ]

In [78]:
flattend

[1, 2, 3, 4, 5]

In [82]:
dict1 = {'a': 10, 'b': 20}
dict2 = {'a': 5, 'c': 7}

merged_dict = dict1.copy()

for key,value in dict2.items():
    if key in merged_dict:
        merged_dict[key] += value
    else:
        merged_dict[key] = value
merged_dict

{'a': 15, 'b': 20, 'c': 7}

In [96]:
dict1 = {'a': 10, 'b': 20}
dict2 = {'a': 5, 'c': 7}

In [107]:
with open('merge1.txt','r') as f:
    print(f.readlines())

['Hi My name is Bhargav']